### PR TITLE
expired-pgp-keys: Fix checking expiration of keys in RPM database

### LINKED ISSUE #2099: expired-pgp-keys plugin checks an expiration key of the freshly downloaded key, not an expiration of the installed key
I'm trying to upgrade rpminspect and librpminspect packages from this Copr repository:

~~~~
baseurl=https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/fedora-$releasever-$arch/ 
gpgkey=https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/pubkey.gpg
~~~~

and I get not unhelpful error message:

~~~
# dnf --assumeyes upgrade 
Updating and loading repositories:
Repositories loaded.
 https://download.copr.fedorainfracloud.org/results/rpmsoftwar 100% |  24.4 KiB/s |   1.0 KiB |  00m00s
 https://download.copr.fedorainfracloud.org/results/dcantrell/ 100% |  24.2 KiB/s |   1.0 KiB |  00m00s
Package                        Arch     Version                                Repository          Size
Upgrading:
 librpminspect                 x86_64   2.1-0.1.202502281937git3d0dde4b.fc43   rpminspect     800.9 KiB
   replacing librpminspect     x86_64   2.1-0.1.202412161945git210c1706.fc42   rpminspect     790.0 KiB
 rpminspect                    x86_64   2.1-0.1.202502281937git3d0dde4b.fc43   rpminspect     374.8 KiB
   replacing rpminspect        x86_64   2.1-0.1.202412161945git210c1706.fc42   rpminspect     377.7 KiB

Transaction Summary:
 Upgrading:          2 packages
 Replacing:          2 packages

Total size of inbound packages is 420 KiB. Need to download 0 B.
After this operation, 8 KiB extra will be used (install 1 MiB, remove 1 MiB).
[1/2] librpminspect-0:2.1-0.1.202502281937git3d0dde4b.fc43.x86 100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded                                                                                 
[2/2] rpminspect-0:2.1-0.1.202502281937git3d0dde4b.fc43.x86_64 100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded                                                                                 
-------------------------------------------------------------------------------------------------------
[2/2] Total                                                    100% |   0.0   B/s |   0.0   B |  00m00s
Running transaction
Transaction failed: Signature verification failed.
OpenPGP check for package "librpminspect-2.1-0.1.202502281937git3d0dde4b.fc43.x86_64" (/var/cache/libdnf5/rpminspect-5528942c86b17233/packages/librpminspect-2.1-0.1.202502281937git3d0dde4b.fc43.x86_64.rpm) from repo "rpminspect" has failed: Problem occurred when opening the package.
~~~

Direct update with rpm explains that the problem is an expired key:

~~~
# rpm -Uvh  ./rpminspect-2.1-0.1.202502281937git3d0dde4b.fc43.x86_64.rpm ./librpminspect-2.1-0.1.202502281937git3d0dde4b.fc43.x86_64.rpm
error: Verifying a signature using certificate FA6386F31766C13FD7B7AB807ACA04AFCBBB3765 (dcantrell_rpminspect (None) <dcantrell#rpminspect@copr.fedorahosted.org>):
  1. Certificate 7ACA04AFCBBB3765 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
  2. Key 7ACA04AFCBBB3765 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
warning: ./rpminspect-2.1-0.1.202502281937git3d0dde4b.fc43.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID cbbb3765: NOTTRUSTED
error: Verifying a signature using certificate FA6386F31766C13FD7B7AB807ACA04AFCBBB3765 (dcantrell_rpminspect (None) <dcantrell#rpminspect@copr.fedorahosted.org>):
  1. Certificate 7ACA04AFCBBB3765 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
  2. Key 7ACA04AFCBBB3765 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
Verifying...                          error: Verifying a signature using certificate FA6386F31766C13FD7B7AB807ACA04AFCBBB3765 (dcantrell_rpminspect (None) <dcantrell#rpminspect@copr.fedorahosted.org>):
  1. Certificate 7ACA04AFCBBB3765 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
  2. Key 7ACA04AFCBBB3765 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
error: Verifying a signature using certificate FA6386F31766C13FD7B7AB807ACA04AFCBBB3765 (dcantrell_rpminspect (None) <dcantrell#rpminspect@copr.fedorahosted.org>):
  1. Certificate 7ACA04AFCBBB3765 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
  2. Key 7ACA04AFCBBB3765 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
error: Verifying a signature using certificate FA6386F31766C13FD7B7AB807ACA04AFCBBB3765 (dcantrell_rpminspect (None) <dcantrell#rpminspect@copr.fedorahosted.org>):
  1. Certificate 7ACA04AFCBBB3765 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
  2. Key 7ACA04AFCBBB3765 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
error: Verifying a signature using certificate FA6386F31766C13FD7B7AB807ACA04AFCBBB3765 (dcantrell_rpminspect (None) <dcantrell#rpminspect@copr.fedorahosted.org>):
  1. Certificate 7ACA04AFCBBB3765 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
  2. Key 7ACA04AFCBBB3765 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2025-02-25T15:11:22Z
################################# [100%]
Preparing...                          ################################# [100%]
        package librpminspect-2.1-0.1.202502281937git3d0dde4b.fc43.x86_64 does not verify: Header V4 RSA/SHA256 Signature, key ID cbbb3765: NOTTRUSTED
        package rpminspect-2.1-0.1.202502281937git3d0dde4b.fc43.x86_64 does not verify: Header V4 RSA/SHA256 Signature, key ID cbbb3765: NOTTRUSTED
~~~~

And indeed the key in RPM database is expired:

~~~~
# rpm -qi gpg-pubkey-cbbb3765-5e57dc1a | gpg --list-packets
# off=0 ctb=99 tag=6 hlen=3 plen=269
:public key packet:
        version 4, algo 1, created 1582816282, expires 0
        pkey[0]: [2048 bits]
        pkey[1]: [17 bits]
        keyid: 7ACA04AFCBBB3765
# off=272 ctb=b4 tag=13 hlen=2 plen=72
:user ID packet: "dcantrell_rpminspect (None) <dcantrell#rpminspect@copr.fedorahosted.org>"
# off=346 ctb=89 tag=2 hlen=3 plen=340
:signature packet: algo 1, keyid 7ACA04AFCBBB3765
        version 4, created 1582816282, md5len 0, sigclass 0x13
        digest algo 8, begin of digest 80 88
        hashed subpkt 33 len 21 (issuer fpr v4 FA6386F31766C13FD7B7AB807ACA04AFCBBB3765)
        hashed subpkt 2 len 4 (sig created 2020-02-27)
        hashed subpkt 27 len 1 (key flags: 2F)
        hashed subpkt 9 len 4 (key expires after 5y0d0h0m)
        hashed subpkt 11 len 4 (pref-sym-algos: 9 8 7 2)
        hashed subpkt 21 len 5 (pref-hash-algos: 10 9 8 11 2)
        hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
        hashed subpkt 30 len 1 (features: 01)
        hashed subpkt 23 len 1 (keyserver preferences: 80)
        subpkt 16 len 8 (issuer key ID 7ACA04AFCBBB3765)
        data: [2047 bits]
~~~~

When I download the key from the web, it has prolonged expiration:

~~~~
# gpg --list-packets pubkey.gpg 
# off=0 ctb=99 tag=6 hlen=3 plen=269
:public key packet:
        version 4, algo 1, created 1582816282, expires 0
        pkey[0]: [2048 bits]
        pkey[1]: [17 bits]
        keyid: 7ACA04AFCBBB3765
# off=272 ctb=b4 tag=13 hlen=2 plen=72
:user ID packet: "dcantrell_rpminspect (None) <dcantrell#rpminspect@copr.fedorahosted.org>"
# off=346 ctb=89 tag=2 hlen=3 plen=340
:signature packet: algo 1, keyid 7ACA04AFCBBB3765
        version 4, created 1709005284, md5len 0, sigclass 0x13
        digest algo 8, begin of digest ac aa
        hashed subpkt 27 len 1 (key flags: 2F)
        hashed subpkt 11 len 4 (pref-sym-algos: 9 8 7 2)
        hashed subpkt 21 len 5 (pref-hash-algos: 10 9 8 11 2)
        hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
        hashed subpkt 30 len 1 (features: 01)
        hashed subpkt 23 len 1 (keyserver preferences: 80)
        hashed subpkt 33 len 21 (issuer fpr v4 FA6386F31766C13FD7B7AB807ACA04AFCBBB3765)
        hashed subpkt 2 len 4 (sig created 2024-02-27)
        hashed subpkt 9 len 4 (key expires after 9y0d12h30m)
        subpkt 16 len 8 (issuer key ID 7ACA04AFCBBB3765)
        data: [2048 bits]
~~~~

I guess this is a perfect use case for the expired-pgp-keys plugin. But I have installed it:

~~~~
# rpm -qa | grep expired-pgp-keys
libdnf5-plugin-expired-pgp-keys-5.2.10.0-20250303010733.58.g97496331.fc43.x86_64
~~~~

it is enabled:

~~~~
# cat /etc/dnf/libdnf5-plugins/expired-pgp-keys.conf 
[main]
name = expired-pgp-keys
enabled = 1
~~~~

Yet, it does not attempt to remove that key from the database:

~~~~
# dnf upgrade 
Updating and loading repositories:
Repositories loaded.
 https://download.copr.fedorainfracloud.org/results/rpmsoftwar 100% |  26.3 KiB/s |   1.0 KiB |  00m00s
 https://download.copr.fedorainfracloud.org/results/dcantrell/ 100% |  24.2 KiB/s |   1.0 KiB |  00m00s
Package                        Arch     Version                                Repository          Size
Upgrading:
 librpminspect                 x86_64   2.1-0.1.202502281937git3d0dde4b.fc43   rpminspect     800.9 KiB
   replacing librpminspect     x86_64   2.1-0.1.202412161945git210c1706.fc42   rpminspect     790.0 KiB
 rpminspect                    x86_64   2.1-0.1.202502281937git3d0dde4b.fc43   rpminspect     374.8 KiB
   replacing rpminspect        x86_64   2.1-0.1.202412161945git210c1706.fc42   rpminspect     377.7 KiB

Transaction Summary:
 Upgrading:          2 packages
 Replacing:          2 packages

Total size of inbound packages is 420 KiB. Need to download 0 B.
After this operation, 8 KiB extra will be used (install 1 MiB, remove 1 MiB).
Is this ok [y/N]: y
[1/2] librpminspect-0:2.1-0.1.202502281937git3d0dde4b.fc43.x86 100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded                                                                                 
[2/2] rpminspect-0:2.1-0.1.202502281937git3d0dde4b.fc43.x86_64 100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded                                                                                 
-------------------------------------------------------------------------------------------------------
[2/2] Total                                                    100% |   0.0   B/s |   0.0   B |  00m00s
Running transaction
Transaction failed: Signature verification failed.
OpenPGP check for package "librpminspect-2.1-0.1.202502281937git3d0dde4b.fc43.x86_64" (/var/cache/libdnf5/rpminspect-5528942c86b17233/packages/librpminspect-2.1-0.1.202502281937git3d0dde4b.fc43.x86_64.rpm) from repo "rpminspect" has failed: Problem occurred when opening the package.
~~~~~

I confirmed with strace that the plugin is loaded. There is no relevant message in the log besides:

~~~~
2025-03-03T09:00:36+0000 [1923] DEBUG Loading plugin library file="/usr/lib64/libdnf5/plugins/expired-p
gp-keys.so"
2025-03-03T09:00:36+0000 [1923] INFO Loaded libdnf plugin "expired-pgp-keys" ("/usr/lib64/libdnf5/plugi
ns/expired-pgp-keys.so"), version="1.0.0"
2025-03-03T09:00:36+0000 [1923] DEBUG Trying to load more plugins using the "expired-pgp-keys" plugin.
2025-03-03T09:00:36+0000 [1923] DEBUG End of loading plugins using the "expired-pgp-keys" plugin.
~~~~

and literally last lines:

~~~~
2025-03-03T09:00:37+0000 [1923] DEBUG [librepo] lr_download: Target: https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/pubkey.gpg (-)
2025-03-03T09:00:37+0000 [1923] DEBUG [librepo] Selecting mirror for: https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/pubkey.gpg
2025-03-03T09:00:37+0000 [1923] INFO [librepo] Downloading: https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/pubkey.gpg
2025-03-03T09:00:37+0000 [1923] DEBUG [librepo] prepare_next_transfer: Resume ignored, existing file was not originally being downloaded by Librepo
2025-03-03T09:00:37+0000 [1923] DEBUG [librepo] lr_download: Downloading started
2025-03-03T09:00:37+0000 [1923] DEBUG [librepo] Transfer finished: https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/pubkey.gpg (Effective url: https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/pubkey.gpg)
~~~~

It seems that the plugin does nothing for me.

### LINKED ISSUE #2108: expired-pgp-keys plugin seems to re-download pub-keys
We shouldn't re-download the pubkeys all the time; but if we really have to,
we shouldn't inform the user like this:

```
Updating and loading repositories:
Repositories loaded.
 https://download.copr.fedorainfracloud.org/results/@mock/mock-deps/pubkey.gpg                                                                                                                      100% |   5.0 KiB/s |   1.0 KiB |  00m00s
 https://download.copr.fedorainfracloud.org/results/@freecad/nightly/pubkey.gpg                                                                   100% |   1.8 KiB/s |   1.7 KiB |  00m01s
 https://download.copr.fedorainfracloud.org/results/@mock/mock/pubkey.gpg                                                                                                                           100% |   3.9 KiB/s | 989.0   B |  00m00s
 https://download.copr.fedorainfracloud.org/results/@copr/copr-dev/pubkey.gpg                                                                                                                       100% |   5.2 KiB/s |   1.0 KiB |  00m00s
Package                                                                          Size ...
Reinstalling:
....
```

Reason: it makes the users concentrate on low-priority info messages.

### PR DESCRIPTION
**Pull request by ppisar**
There was a flaw in what this plugin did: Instead of checking an expiration time of the keys in an RPM database, it downloaded keys of enabled repositories from the Internet and checked their expiration time. As a side effect, this plugin repeatedly downloaded the keys on every invocation.

This patch fixes both the issues by checking keys which are in the RPM database instead.

The new implementation removes all expired and confirmed keys in a single RPM transaction. It also removes the unnecessary crosscheck that a key obtained from an RPM database axtually exists in the database. All that speeds up the operation at the expense that reporting a success of the removal happens after the user selecting all the keys for the removal.

The user query now reports a fingerprint instead of a path to the key file. The reason is that a name of the key file is a temporary file now because we take the keys from the RPM database. The current API does allow importing from memory, neither changing the file attribute of KeyInfo object.

This patch intentionally does not enhance any interface, inluding newly identified bugs to be fixed independenlty later:

Respect --install-root option. We should probably move some code to libdnf5/rpm/rpm_signature.cpp, or expose more code from there.

libdnf5::repo callbacks API is badly designed as it cannot be used independetly from libdnf5::repo::RepoQuery object. That interface should be moved closer to base as it is deals with a user interface and not the repositories.

Resolves #2099
Resolves #2108

### CODE REVIEW

**Comment by ppisar** [comment]
@jan-kolarik, maybe you are interested in this patch as you are an author of this plugin.

**Comment by ppisar** [comment]
The dnf5-test fails because I corrected an output message from "The following PGP key" to "The following OpenPGP key". I will prepare an amendment for ci-dnf-stack.

**Comment by ppisar** [comment]
The ci-dnf-stack fix is at <https://github.com/rpm-software-management/ci-dnf-stack/pull/1651>.

**Comment by pmatilai** [comment]
Just a heads-up / for general awareness: rpm 6.0 will have a dedicated API for managing keys, and official support for non-rpmdb keyrings. 

Manipulating gpg-pubkey "packages" directly is the only option in 4.x of course so nothing wrong with doing that now, but try to avoid introducing new mentions of "keys in rpmdb" in user visible messages and documentation, its better to talk about "persistent rpm keystore" or something like that. There aren't any such messages here so that's ok. Commit messages talking about rpmdb is fine when that's exactly what it does :sweat_smile:

File: libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp [hunk 1]
```diff
@@ -175,39 +154,85 @@ void ExpiredPgpKeys::process_expired_pgp_keys(const libdnf5::base::Transaction &
...
+    std::vector<libdnf5::rpm::KeyInfo> keys_to_remove;
+
+    while ((h = rpmdbNextIterator(mi)) != nullptr) {
+        char * raw_key = headerGetAsString(h, RPMTAG_DESCRIPTION);
+        if (!raw_key)
             continue;
+
+        // Serialize raw key into a file becuse parse_key_file() requires a file.
+        // (Or use lr_gpg_import_key_from_memory() directly?)
+        auto key_tfile = libdnf5::utils::fs::TempFile("key");
```
Comment (jan-kolarik) [inline libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp:185]: This worries me a bit - when there's an issue with creating the temporary file and an exception is thrown, every DNF transactional operation crashes. I'm not sure if that's necessary since I see this more as an additional feature for users. That said, we're already doing the same thing when checking GPG signatures and parsing keys with `RpmSignature::parse_key_file`, so maybe we should just create an issue to address this in the future.

**Review by jan-kolarik — COMMENTED** [review]
Overall, it looks great - thanks, Petr! I tested it locally and didn't run into any issues. I still plan to file a few issues, including the ones you mentioned in the description, plus improving the existing CI test to properly cover this scenario with the updated prolonged key.

File: libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp (hunk 1 above)
Comment (ppisar) [reply libdnf5-plugins/expired-pgp-keys/expired-pgp-keys.cpp:185]: With "every DNF transactional operation crashes" do you mean just the transaction in this plugin, or any independent transaction in further DNF code, like installing packages?

With the first meaning I think it's acceptable: If you cannot create a temporary file now, you will very probably get the same failure for other keys. So it does not make sense to try processing other keys. The exception will get wrapped into a plugin exception and hopefully reported to the user as a plugin failure. (I did not test it.)

If the plugin failure causes DNF to abort, then it's a question of whether we want to handle this plugin as an optional, or required for the DNF work flow. I think it's a completely independent question, which the old code also did not solve.

If a point of your comment is the latter, then it's unfortunate. But I'd like to keep this pull request limited to the two issues it claims to resolve. I'd rather fix the exception handling in this plugin together separately, together with setting an installroot, preferably by exposing correct helper methods from libdnf5 so that we do not have multiple implementations.

**Review by jan-kolarik — APPROVED** [review]
