### PR TITLE
fix: unify epoch display across all DNF5 commands

### LINKED ISSUE #1175: Unify epoch usage in DNF5
Epoch is not handled consistently in DNF, DNF5, RPM

RPM does not show 0 epoch for `rpm -q B`

RPM shows 0 epoch  `rpm -q B --qf "%{name}-%{evr}\n" when `Epoch: 0` in in spec.

`rpmbuild` does not add epoch to rpm file name.

DNF/DNF5 and command repoquery always shows 0 epoch.

DNF/DNF5 transaction table does not show 0 epoch.

DNF transaction summary does not show 0 epoch.

DNF history info does not show 0 epoch for transaction packages.

DNF5 history info shows 0 epoch for transaction packages.

DNF5 and `Package.to_string()` returns optional epoch as well as Python binding `str(Package)`

DNF5 uses full NEVRA in scriptlets: Running trigger-install scriptlet: man-db-0:2.11.2-2.fc38.x86_64

Createrepo_c always adds 0 epoch to metadata

_Originally posted by @j-mracek in https://github.com/rpm-software-management/dnf5/pull/1092#discussion_r1447308700_

### PR DESCRIPTION
**Pull request by fhbash**
Always show epoch (including 0) in package NEVRA strings for consistency. Updates Package::to_string(), transaction table, daemon API, and transaction replay.

Fixes inconsistent epoch handling where some commands showed epoch and others didn't.

Closes #1175

### CODE REVIEW

File: include/libdnf5/rpm/package.hpp [hunk 1]
```diff
@@ -146,13 +146,15 @@ class LIBDNF_API Package {
     std::string get_arch() const;
 
     /// @return RPM package EVR (Epoch:Version-Release). If the Epoch is 0, it is omitted from the output.
+    /// @deprecated Use separate components or full NEVRA for consistent epoch display
```
Comment (kontura) [inline include/libdnf5/rpm/package.hpp]: Do we really want to deprecate these?
I would be fine with leaving them on the API.

**Review by kontura — COMMENTED** [review]
I like this change but personally I would treat it as an API break.

File: include/libdnf5/rpm/package.hpp (hunk 1 above)
Comment (fhbash) [reply include/libdnf5/rpm/package.hpp]: I don't have strong opinion on this, my thought to deprecated is warning API users is better to use full nevra, but I'm good to leave them like it was if it is the case

**Review by dcantrell — CHANGES_REQUESTED** [review]
I also agree that this constitutes an API break.  Epoch is an odd one in the RPM space.  Many packagers and users do not understand it and that has led to some packages receiving Epoch updates when they should not have.  Most packages have '0' as the Epoch and then you have a number of them with crazy high epoch values.

I think if dnf5 were to start showing epoch all the time it would lead to further misuse of epoch among users and package maintainers.  I would like to see this functionality added to dnf5 as an option you can turn on via the config file, but leave the default as-is.  That brings in the new functionality but does not break the API as we have it now.  Minimal disruption.

File: include/libdnf5/rpm/package.hpp (hunk 1 above)
Comment (fhbash) [reply include/libdnf5/rpm/package.hpp]: Reverted these changes as suggested.

File: dnf5daemon-server/package.cpp [hunk 2]
```diff
@@ -329,10 +329,19 @@ std::string package_to_json(const libdnf5::rpm::Package & libdnf_package, const
...
                 break;
             case PackageAttribute::evr:
-                json_object_object_add(json_pkg, cattr, json_object_new_string(libdnf_package.get_evr().c_str()));
+                // Always show epoch in EVR (epoch:version-release)
+                {
+                    std::string evr_with_epoch = libdnf_package.get_epoch();
+                    if (evr_with_epoch.empty()) {
+                        evr_with_epoch = "0";
+                    }
+                    evr_with_epoch += ":" + libdnf_package.get_version() + "-" + libdnf_package.get_release();
```
Comment (dcantrell) [inline dnf5daemon-server/package.cpp:338]: This will lead to a NEVRA string starting with ":" if epoch is empty, or an exception if string concatenation can't turn an empty string in to "".

File: libdnf5-cli/output/transaction_table.cpp [hunk 3]
```diff
@@ -336,7 +336,13 @@ TransactionTable::Impl::Impl(ITransaction & transaction) {
         // column. Thus adding a indentation manualy.
         scols_line_set_data(ln, COL_NAME, (" " + pkg->get_name()).c_str());
         scols_line_set_data(ln, COL_ARCH, pkg->get_arch().c_str());
-        scols_line_set_data(ln, COL_EVR, pkg->get_evr().c_str());
+        // Always show epoch in EVR (epoch:version-release)
+        std::string evr_with_epoch = pkg->get_epoch();
+        if (evr_with_epoch.empty()) {
+            evr_with_epoch = "0";
+        }
+        evr_with_epoch += ":" + pkg->get_version() + "-" + pkg->get_release();
```
Comment (dcantrell) [inline libdnf5-cli/output/transaction_table.cpp:344]: See above about the leading ":".

**Review by dcantrell — APPROVED** [review]
Looks good to me now, thanks.

**Comment by kontura** [comment]
Note also that the CI tests are failing (see the [checks](https://github.com/rpm-software-management/dnf5/pull/2447/checks)), looks like some of that are valid problems, in particular I think there is a problem with replaying transactions. However some other tests will simply need to be updated as they expect nevras without 0 epoch.

The CI is here: https://github.com/rpm-software-management/ci-dnf-stack/

Feel free to ping me if you would like some help with that.

File: dnf5daemon-server/package.cpp (hunk 2 above)
Comment (fhbash) [reply dnf5daemon-server/package.cpp:338]: With this change, I believe we'll always have epoch = 0

File: libdnf5-cli/output/transaction_table.cpp (hunk 3 above)
Comment (fhbash) [reply libdnf5-cli/output/transaction_table.cpp:344]: See above comment

File: libdnf5/transaction/transaction_sr.cpp [hunk 4]
```diff
@@ -346,8 +346,8 @@ TransactionReplay to_replay(libdnf5::transaction::Transaction & trans) {
     for (const auto & pkg : trans.get_packages()) {
         PackageReplay package_replay;
 
-        // Use to_nevra_string in order to have nevra wihtout epoch if it is 0
-        package_replay.nevra = rpm::to_nevra_string(pkg);
+        // Use to_full_nevra_string to always include epoch (including 0 if epoch is empty)
+        package_replay.nevra = rpm::to_full_nevra_string(pkg);
```
Comment (kontura) [inline libdnf5/transaction/transaction_sr.cpp]: I think this is the only problematic change left.
The `PackageReplay` assumes that the nevra doesn't include epoch if its 0: https://github.com/rpm-software-management/dnf5/blob/main/libdnf5/transaction/transaction_sr.hpp#L64-L65
You either have to go through all the places where it is used and check if its ok with always present 0 (it is causing problems at least with `rpm_reason_overrides`) or it might be ok to drop this change. 
This will not affect any dnf CLI text output and we could file a separate issue to change this later on. I think it is easier to have more smaller changes than one big one.

Comment (fhbash) [reply libdnf5/transaction/transaction_sr.cpp]: get it..I believe you're right, since removing this will not affect the cli output, I believe it's will be better to have this change in another Issue/PR.

I created this new issue https://github.com/rpm-software-management/dnf5/issues/2477  to work with it in the next near future, and I'll remove this change for this PR.

thanks!

**Review by kontura — COMMENTED** [review]
Thanks.

I think that now https://github.com/rpm-software-management/ci-dnf-stack/pull/1765 needs an update. I believe that all the PR has to do is just a few smaller changes adding the 0 epoch in a couple places in these 4 files: install-package-ursine.feature, transaction-output.feature, replay-errors.feature and replay.feature.

**Comment by kontura** [comment]
Thank you!
