### PR TITLE
Add/fix documentation for rpm::PackageQuery methods

### LINKED ISSUE #1320: Some filters in rpm/package_query.hpp are not documented
- filter_description - incorrect doc
- filter_installed()
- filter_available()
- filter_upgrades()
- filter_upgradable()
- filter_downgrades()
- filter_downgradable()

Related: https://github.com/rpm-software-management/dnf5/pull/1310

### PR DESCRIPTION
**Pull request by jrohel**
Closes #1320

### CODE REVIEW

File: include/libdnf5/rpm/package_query.hpp [hunk 1]
```diff
@@ -847,19 +847,45 @@ class PackageQuery : public PackageSet {
...
+    /// Filter installed packages.
+    ///
+    /// Removes from the query all packages that are not installed.
+    /// @since 5.0
+    // @replaces libdnf/sack/query.hpp:method:installed()
     void filter_installed();
 
+    /// Filter available packages.
+    ///
+    /// Removes from the query all packages that are installed.
```
Comment (m-blaha) [inline include/libdnf5/rpm/package_query.hpp:859]: Nice, I like the way how you dealt with definition of what "available package" actually means.

**Review by m-blaha — APPROVED** [review]
Thank you!
