### PR TITLE
downloaders: Pass fail_fast and resume by setters

### LINKED ISSUE #528: Improve the download methods API
Current `download` methods for the `FileDownloader` and `PackageDownloader` are passing two `bool` parameters:
- `fail_fast`: whether to fail the whole download on a first error or keep downloading.
- `resume`: whether to try to resume the download if a destination package already exists.

It would be probably better to use the `download` method without arguments and introduce new setters on the `*Downloader` classes to configure these values to see the workflow of the individual operations more clearly.

### PR DESCRIPTION
**Pull request by jan-kolarik**
To make the API and code usages more explicit.

Closes #528.
CI tests fix: https://github.com/rpm-software-management/ci-dnf-stack/pull/1297.

### CODE REVIEW

File: include/libdnf/repo/package_downloader.hpp [hunk 1]
```diff
@@ -53,9 +53,17 @@ class PackageDownloader {
...
+
+    /// Configure whether to fail the whole download on a first error or keep downloading.
+    /// @param value If true, download will fail on the first error, otherwise it continues.
+    /// This is set to true by default.
+    void set_fail_fast(bool value);
+
+    /// Configure whether to try resuming the download if a destination package already exists.
+    /// @param value If true, download is tried to be resumed, otherwise it starts over.
+    /// This is set to true by default.
+    void set_resume(bool value);
```
Comment (j-mracek) [inline include/libdnf/repo/package_downloader.hpp:66]: In this approach the behavior will be not modifiable from DNF5 manager. Only API user can make a decision what approach should be used. Could you imagine a situation when resume would create problem?

File: include/libdnf/repo/package_downloader.hpp [hunk 2]
```diff
@@ -53,9 +53,17 @@ class PackageDownloader {
...
     /// Download the previously added packages.
-    /// @param fail_fast Whether to fail the whole download on a first error or keep downloading.
-    /// @param resume Whether to try to resume the download if a destination package already exists.
-    void download(bool fail_fast, bool resume);
+    void download();
+
+    /// Configure whether to fail the whole download on a first error or keep downloading.
+    /// @param value If true, download will fail on the first error, otherwise it continues.
+    /// This is set to true by default.
+    void set_fail_fast(bool value);
```
Comment (j-mracek) [inline include/libdnf/repo/package_downloader.hpp:61]: I think that for fail_fast it is the best approach. :)

**Review by j-mracek — COMMENTED** [review]
The PR looks good, but I am not sure only about `void set_resume(bool value);`

File: include/libdnf/repo/package_downloader.hpp (hunk 1 above)
Comment (jan-kolarik) [reply include/libdnf/repo/package_downloader.hpp:66]: If we would provide configuration options for `resume` or `fail_fast` then I understand it like these values would have global meaning. But we are already using specific values for different scenarios inside the libdnf. So the question is, how it will work then? Should the user configuration override the values we currently pass to the downloader in the library?

Comment (j-mracek) [reply include/libdnf/repo/package_downloader.hpp:66]: make sense, I overlooked the internal modification for download pgpkeys. it makes no sense to resume interrupted downloads for very small files.

**Comment by j-mracek** [comment]
I've tested the PR locally and everything is ok.
